### ISSUE TITLE
this have a error on linux centos!

### ISSUE THREAD

**Issue by checkblue** [tzumby/ex_keccak#20]
[***@xxxx blockscout]# mix deps.compile ex_keccak
==> ex_keccak
Compiling 1 file (.ex)

== Compilation error in file lib/ex_keccak.ex ==
** (ErlangError) Erlang error: :enoent
    (elixir 1.12.3) lib/system.ex:1041: System.cmd("cargo", ["metadata", "--format-version=1"], [cd: "native/exkeccak"])
    (rustler 0.22.2) lib/rustler/compiler/config.ex:81: Rustler.Compiler.Config.external_resources/2
    (rustler 0.22.2) lib/rustler/compiler/config.ex:69: Rustler.Compiler.Config.build/1
    (rustler 0.22.2) lib/rustler/compiler.ex:9: Rustler.Compiler.compile_crate/2
    lib/ex_keccak.ex:2: (module)
could not compile dependency :ex_keccak, "mix compile" failed. You can recompile this dependency with "mix deps.compile ex_keccak", update it with "mix deps.update ex_keccak" or clean it with "mix deps.clean ex_keccak"

**I erlang version：**
Erlang/OTP 23 [erts-11.1.7] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:1] [hipe]
Eshell V11.1.7  (abort with ^G)

**Elixir version:** 
Elixir 1.12.3 (compiled with Erlang/OTP 22)

**Comment by Nickforall** [comment]
You need to have the rust compiler/cargo installed :) This error indicates you don't or it is not in your PATH.

**Comment by tzumby** [comment]
Closing this, I think @Nickforall pretty much answered the question.

**Comment by Cori1109** [comment]
Thanks Nickforall.

**Comment by AkshayImmanent** [comment]
![image](https://user-images.githubusercontent.com/102202932/185580544-bbfb8f06-8ff4-4545-8f79-21f4c852c126.png)


We have the same issue rustc and cargo are preinstalled.
