### ISSUE TITLE
Cannot load ExKeccak on Mac M1 Pro

### ISSUE THREAD

**Issue by grahac** [tzumby/ex_keccak#21]
I tried installing ex_keccak on a new Mac m1 but got an error when trying to install.

Specifically got a message that 

/_build/dev/lib/ex_keccak/priv/native/libexkeccak.so,\' (mach-o file, but is an incompatible architecture (have \'x86_64\', need \'arm64e\'))

Anyone experience this before? Is there a way to get ExKeccak working on M1 Mac architectures?  

Thanks!

**Comment by grahac** [comment]
For those keeping track at home, I had two versions of Rust on my computer (one that was copied from the old computer). Uninstalling rust and re-installing fixed this problem.

**Comment by tzumby** [comment]
Thanks for following up @grahac! I didn't get a chance to look at your issue but I'm glad you figured it out.
