### ISSUE TITLE
Can't use library for arm architecture

### ISSUE THREAD

**Issue by JulesGuesnon** [tzumby/ex_keccak#27]
Hello!

I'm using a library that is using this library, and when I run the code I get this error: 

```
[warning] The on_load function for module Elixir.ExKeccak returned:
{:error,
 {:load_failed,
  'Failed to load NIF library: \'dlopen(/Users/julesguesnon/Dev/Tinybones/tinybones-game-server/_build/dev/lib/ex_keccak/priv/native/libexkeccak.so, 0x0002): tried: \'/Users/julesguesnon/Dev/Tinybones/tinybones-game-server/_build/dev/lib/ex_keccak/priv/native/libexkeccak.so\' (mach-o file, but is an incompatible architecture (have \'x86_64\', need \'arm64e\')), \'/usr/local/lib/libexkeccak.so\' (no such file), \'/usr/lib/libexkeccak.so\' (no such file), \'/Users/julesguesnon/Dev/Tinybones/tinybones-game-server/deps/ex_keccak/priv/native/libexkeccak.so\' (mach-o file, but is an incompatible architecture (have \'x86_64\', need \'arm64e\')), \'/usr/local/lib/libexkeccak.so\' (no such file), \'/usr/lib/libexkeccak.so\' (no such file)\''}}
```

And IMO the most important part is this one: `(mach-o file, but is an incompatible architecture (have \'x86_64\', need \'arm64e\'))`. It's probably happening because I'm running the code on the Mac M1.

Would it be possible to ship an arm compatible version as well?

**Comment by JulesGuesnon** [comment]
Actually I tried creating a new rustler nif from scratch and I got the same error, so I'll open an issue on the rustler repo and make a PR if something needs to be updated later

**Comment by tzumby** [comment]
Hey @JulesGuesnon, my guess is that we probably need another entry similar to this one here for arm ? 

https://github.com/tzumby/ex_keccak/blob/master/native/exkeccak/.cargo/config

**Comment by joshuataylor** [comment]
aarch64 is arm, it's just another name for it (The naming scheme is confusion, ARM64, ARM64e, AARCH64, Apple Silicon..)

You could also add the following for all Macs:
```
[target.'cfg(target_os = "macos")']
```

**Comment by tzumby** [comment]
that's right, i keep forgetting the m1 is arm. in that case this is odd, i can definitely compile this on my m1.

**Comment by JulesGuesnon** [comment]
As mentioned in [this issue](https://github.com/rusterlium/rustler/issues/459), my toolchain was an `x86_64` one, so I changed it to `aarch64` and now it's good, thanks for your help!
