### ISSUE TITLE
Compilation fails on otp 24

### ISSUE THREAD

**Issue by ayrat555** [tzumby/ex_keccak#7]
it seems rustler doesn't support otp 24 yet

**Comment by tzumby** [comment]
thanks for opening this! i'll keep an eye on the progress here 👍

**Comment by tzumby** [comment]
@ayrat555, looks like I can't publish this as long as we have a release candidate for `rustler`:

```
> mix hex.publish
** (Mix) A stable package release cannot have a pre-release dependency
```

I'll push a quick update once `0.22.0` is out.

**Comment by ayrat555** [comment]
@tzumby what do you think about releasing a pre-release version of the library. for example `0.2.0-rc.1` ?

**Comment by artob** [comment]
> @tzumby what do you think about releasing a pre-release version of the library. for example `0.2.0-rc.1` ?

This would indeed be very helpful for all of us trying to use this package currently!

**Comment by tzumby** [comment]
Definitely open to that, I can prepare the rc release right now

**Comment by tzumby** [comment]
Done: https://hex.pm/packages/ex_keccak/0.2.0-rc.1
